Fix database session locks
interchange/interchange pull request #147
Opened 2024-03-18 22:58 UTC by pullingshots

The LOCKLOOP block was missing a while statement which according to Perl docs means that it is semantically identical to a loop that executes once, and a next statement will simply exit the block early.
So, when a session lock was found, it exited out of the LOCKLOOP block, ending up in "# Should never get here", bypassing the lock.

Additionally, the $locktime and $pid variables were not being cleared when the lock was cleared, causing the current pid to write a new lock and use it to block itself indefinitely.

2024-03-18 23:12 UTC, jonjensen approved these changes
Great find, Andrew!

On your explanation of the bug, thinking out loud, another way to look at it is that the `next` was a mistake and should have been a `redo`. As I read it, this would have worked.

I'm not saying anything in your commit should change, just playing software archaeologist thinking about what may have been intended.

2024-03-19 02:05 UTC, msjohns1 commented
> On your explanation of the bug, thinking out loud, another way to look at it is that the `next` was a mistake and should have been a `redo`. As I read it, this would have worked.

Exactly my first thought!

Thanks for digging through that, @pullingshots!

2024-03-19 16:22 UTC, msjohns1 requested changes
Changes on "should never get here" should be done now, IMO. We can discuss the sleep changes separately, and whether I haven't considered some aspect of the current algorithm sufficiently.

2024-03-19 17:04 UTC, jonjensen commented on lib/Vend/Session.pm
Agreed that if we "should never get here", let's die.

On limiting the sleep time: Sounds good. I can imagine this hitting a database pretty hard with hundreds of sessions waiting and retrying once per second, but the overall system has bigger problems anyway if that's the situation. So seems good.

2024-03-21 16:17 UTC, jonjensen commented
@pullingshots In the interest of getting this bugfix out there, would you be game to take Mark's suggestion to make a minimal change now to `die` rather than `return` if the "should never get here" code is hit? If your testing shows that's good, then I think we have a nice minimal bugfix pull request here.

The timing thing Mark brought up can and should be a separate change IMO.

2024-03-21 17:16 UTC, msjohns1 approved these changes

2024-03-21 17:37 UTC, jonjensen approved these changes

2024-03-21 17:44 UTC, pullingshots commented on lib/Vend/Session.pm
I did some testing of changing the sleep algorithm to a fixed 1s and I agree with Mark that it makes more sense that way. The one thing I did run into is when you have multiple requests waiting for the same lock, it is not predictable which one will see the released lock first. So they will not necessarily get processed in the order they were requested. With the current sleep algorithm it is actually more likely that the last request will see the lock release first because it will have the shortest sleep duration. So, we should address that as well because I believe the expected behavior is that requests are processed in order.

I do have an experimental session lock wait queue that has been in production now for some time now which may address both of these issues. It has the added benefit that you can set a max number of requests waiting for any given lock and it will reject new requests over the max until the lock is released. I'll work on getting a PR out for that.

2024-03-21 17:55 UTC, merged

2024-03-21 18:32 UTC, msjohns1 commented on lib/Vend/Session.pm
Yeah, I was walking through the logic of that locking algorithm and had some questions. I even wondered if there was a race condition, where multiple processes could grab a lock after release but before a subsequent process to create a new lock record. Looking forward to seeing your wait queue!